site_name: Big Data Tutorial - Hortonworks Data Platform
theme:
  name: material
  palette:
    primary: indigo
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true