site_name: Big Data Tutorial - Hortonworks Data Platform
theme:
  name: material
  palette:
    primary: indigo
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Introduction: index.md
  - Prerequisites: prerequisites.md
